### ISSUE TITLE
Getting "No documents indexed" even though wikipedia folder is in the current working directory

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [cohere-ai/BinaryVectorDB#2]
I'm running the code from the README after wget'ing the index, but I get this error:

```
Query: Who is the founder of Facebook
Traceback (most recent call last):
  File "/Users/dhruvanand/Code/bvdb/bvdb-try.py", line 11, in <module>
    hits = db.search(query)
  File "/Users/dhruvanand/miniforge3/lib/python3.10/site-packages/BinaryVectorDB/BinaryVectorDB.py", line 143, in search
    raise Exception("No documents indexed. Please add documents before searching.")
Exception: No documents indexed. Please add documents before searching.
```

Are there any extra steps?

**Comment by nreimers** [comment]
How does the folder look like you point the code at? Does it contain a config.json?

Make sure the config.json and other files are not in a subfolder

**Comment by dhruv-anand-aintech** [comment]
contents of `bvdb-try.py`:
```
from BinaryVectorDB import BinaryVectorDB
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())
# Point it to the unzipped folder from the previous step
# Ensure that you have set your Cohere API key via: export COHERE_API_KEY=<<YOUR_KEY>>
db = BinaryVectorDB("wikipedia-2023-11-simple/")

query = "Who is the founder of Facebook"
print("Query:", query)
hits = db.search(query)
for hit in hits[0:3]:
    print(hit)

```
Tree:
```
.
├── bvdb-try.ipynb
├── bvdb-try.py
├── wikipedia-2023-11-simple
│   ├── config.json
│   └── docs
│       ├── 000016.log
│       ├── CURRENT
│       ├── IDENTITY
│       ├── LOCK
│       ├── LOG
│       ├── LOG.old.1713160456197937
│       ├── LOG.old.1713245570458511
│       ├── LOG.old.1713245590633805
│       ├── MANIFEST-000017
│       ├── OPTIONS-000015
│       ├── OPTIONS-000019
│       └── rocksdict-config.json
└── wikipedia-2023-11-simple.zip

3 directories, 16 files
```

**Comment by nreimers** [comment]
What is the load dotenv? Is it changing your Python workdir?

Can you try without it?

Also in the python code, check if the Config.json can be found at the expected path.

**Comment by dhruv-anand-aintech** [comment]
removed the load_dotenv and set the cohere key directly in the code:
printed os.path.exists for various things:
```
python bvdb-try.py                                 [24/04/17| 4:19PM]
os.path.exists("wikipedia-2023-11-simple/")=True
os.path.isdir("wikipedia-2023-11-simple/")=True
os.path.exists("wikipedia-2023-11-simple/config.json")=True
Query: Who is the founder of Facebook
Traceback (most recent call last):
  File "/Users/dhruvanand/Code/bvdb/bvdb-try.py", line 18, in <module>
    hits = db.search(query)
  File "/Users/dhruvanand/miniforge3/lib/python3.10/site-packages/BinaryVectorDB/BinaryVectorDB.py", line 143, in search
    raise Exception("No documents indexed. Please add documents before searching.")
Exception: No documents indexed. Please add documents before searching.
```

**Comment by dhruv-anand-aintech** [comment]
actually, there's something wrong with my unzipped wiki directory:
![Screenshot 2024-04-17 at 4 25 34 PM](https://github.com/cohere-ai/BinaryVectorDB/assets/105786647/ddf81847-72fc-4462-9cc5-a6d8bf55608c)

**Comment by dhruv-anand-aintech** [comment]
re-unzipped and it works fine

**Comment by nreimers** [comment]
Great to hear this :)
